The above data is data for prebid auctions. There are bidders who receive requests for placing ads, they respond to these requests with a bid and the highest bid wins the auction. Analyze the dataset to answer which bidder has the highest win rate (wins / total_bid).

In [1]:
import pandas as pd
import numpy as np

In [23]:
df=pd.read_csv("analysis_id(in).csv")
df.sample(10)

,Unnamed: 0,date_hour,client,device_type,time_zone,os_name,browser_name,ad_unit,size,bidder,...,sum_time_to_respond,median,min_bid,max_bid,avg_bid,sum_2nd_highest_bid,sum_prebid_winning_bid,sum_winning_bid,sum_nobid,sum_timeout
1214,1214,2021-04-11T01:00:00,asc126828,Desktop,America/New_York,Windows,Chrome-89.04389114,div-gpt-ad-BT-D-InPost-8_2_4,728x90,pubmatic,...,237.0,0.0094,0.00940,0.009400,0.009400,NaN,NaN,NaN,NaN,NaN
863,863,2021-04-11T01:00:00,asc126828,Desktop,America/Los_Angeles,Windows,Chrome-89.04389114,div-gpt-ad-BT-D-SideBar-1,300x250,sharethrough,...,9335.0,0.2790,0.27900,0.299925,0.289463,NaN,0.87885,NaN,NaN,NaN
192,192,2021-04-11T01:00:00,asc126828,Desktop,America/Chicago,Windows,Chrome-89.04389114,div-gpt-ad-BT-D-InPost-7_1_3,468x60,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2827,2827,2021-04-11T01:00:00,asc126828,Desktop,America/Chicago,Windows,Chrome-89.04389114,div-gpt-ad-BT-D-InPost-4_1_6,336x280,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1590,1590,2021-04-11T01:00:00,asc126828,Desktop,America/New_York,Windows,Chrome-89.04389114,div-gpt-ad-BT-T-InPost-6_1_4,300x250,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4975,4975,2021-04-11T01:00:00,asc126828,Desktop,America/New_York,Windows,Chrome-89.04389114,div-gpt-ad-BT-D-InPost-4_1_29,728x90,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2537,2537,2021-04-11T01:00:00,asc126828,Desktop,America/New_York,Windows,Chrome-89.04389114,div-gpt-ad-BT-D-Responsive-BF,728x90,pulsepoint,...,108.0,NaN,1.17600,1.176000,1.176000,NaN,1.17600,NaN,NaN,NaN
3701,3701,2021-04-11T01:00:00,asc126828,Desktop,America/Chicago,Windows,Chrome-89.04389114,div-gpt-ad-BT-D-InLine-1,300x250,pubmatic,...,50760.0,0.1598,0.10340,0.197400,0.149583,NaN,NaN,NaN,NaN,NaN
2757,2757,2021-04-11T01:00:00,asc126828,Desktop,UTC,Windows,Chrome-51.0270463,div-gpt-ad-BT-D-InPost-7_1_3,300x250,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4362,4362,2021-04-11T01:00:00,asc126828,Desktop,America/Detroit,Macintosh,Chrome-89.04389114,div-gpt-ad-BT-D-SideBar-1,300x250,medianet,...,2364.0,NaN,0.20116,0.201160,0.201160,NaN,NaN,NaN,NaN,NaN

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 27 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Unnamed: 0              5000 non-null   int64
 1   date_hour               5000 non-null   object
 2   client                  5000 non-null   object
 3   device_type             5000 non-null   object
 4   time_zone               5000 non-null   object
 5   os_name                 5000 non-null   object
 6   browser_name            5000 non-null   object
 7   ad_unit                 5000 non-null   object
 8   size                    5000 non-null   object
 9   bidder                  5000 non-null   object
 10  bid_range               5000 non-null   object
 11  media_type              5000 non-null   object
 12  request_count           5000 non-null   int64
 13  response_count          5000 non-null   int64
 14  prebid_win_count        1167 non-null   float64
 15  win_count               186 non-null    float64
 16  sum_bid                 3790 non-null   float64
 17  sum_time_to_respond     3790 non-null   float64
 18  median                  1760 non-null   float64
 19  min_bid                 3790 non-null   float64
 20  max_bid                 3790 non-null   float64
 21  avg_bid                 3790 non-null   float64
 22  sum_2nd_highest_bid     734 non-null    float64
 23  sum_prebid_winning_bid  1167 non-null   float64
 24  sum_winning_bid         186 non-null    float64
 25  sum_nobid               0 non-null      float64
 26  sum_timeout             0 non-null      float64
dtypes: float64(13), int64(3), object(11)
memory usage: 1.0+ MB

In [18]:
new_df=df.copy()

In [20]:
new_df['win_count'].fillna(df['win_count'].mean(),inplace=True)
new_df['win_count'].isna().sum()

0

In [21]:
new_df['response_count'].sum()

21524

In [17]:
df.describe()

,Unnamed: 0,request_count,response_count,prebid_win_count,win_count,sum_bid,sum_time_to_respond,median,min_bid,max_bid,avg_bid,sum_2nd_highest_bid,sum_prebid_winning_bid,sum_winning_bid,sum_nobid,sum_timeout
count,5000.000000,5000.00000,5000.000000,1167.000000,186.000000,3790.000000,3790.000000,1760.000000,3790.000000,3790.000000,3790.000000,734.000000,1167.000000,186.000000,0.0,0.0
mean,2499.500000,56.64960,4.304800,2.875750,1.494624,1.687932,3601.955145,0.969637,0.662073,0.677288,0.669344,0.880864,1.503674,1.517776,NaN,NaN
std,1443.520003,632.18282,15.858846,6.852213,1.661153,3.275426,10546.457681,1.228221,0.940156,0.935942,0.938137,1.112114,2.106157,2.738279,NaN,NaN
min,0.000000,1.00000,0.000000,1.000000,1.000000,0.008405,51.000000,0.008460,0.005967,0.008405,0.008405,0.009400,0.008460,0.051480,NaN,NaN
25%,1249.750000,1.00000,1.000000,1.000000,1.000000,0.253432,471.000000,0.174600,0.133000,0.161468,0.145500,0.198510,0.370900,0.464071,NaN,NaN
50%,2499.500000,2.00000,1.000000,1.000000,1.000000,0.738943,994.500000,0.533610,0.313041,0.347949,0.337312,0.561049,0.905610,0.969600,NaN,NaN
75%,3749.250000,16.00000,2.000000,2.000000,1.000000,1.836004,2341.250000,1.320570,0.814800,0.827241,0.824068,1.123550,1.734954,1.763130,NaN,NaN
max,4999.000000,21855.00000,348.000000,144.000000,16.000000,87.057500,177874.000000,9.670900,9.670900,9.670900,9.670900,8.620920,26.505200,34.483680,NaN,NaN

In [6]:
df.shape

(5000, 27)

In [12]:
df['sum_winning_bid'].isna().sum()

4814

In [14]:
df['sum_winning_bid'].mean()

1.5177760322580647

In [15]:
df['sum_winning_bid'].min()

0.05148

In [24]:
new_df['win_count'].sum()

7473.118279569891

In [32]:
new_df['response_count'].isna().sum()

0

In [ ]:
win_rate=wins(proportion of total auctions where a bid wins)/(total_bids)% of bid that win auction (total_bids)

In [35]:
df['Count_of_wins']=df.groupby(['bidder']).agg(wins=('win_count',sum),(total_bids=('response_count',sum))

In [36]:
df

,Unnamed: 0,date_hour,client,device_type,time_zone,os_name,browser_name,ad_unit,size,bidder,...,min_bid,max_bid,avg_bid,sum_2nd_highest_bid,sum_prebid_winning_bid,sum_winning_bid,sum_nobid,sum_timeout,win_rate,Count_of_wins
0,0,2021-04-11T01:00:00,asc126828,Desktop,America/Chicago,Linux,Chrome-85.04183133,div-gpt-ad-BT-D-Footers,728x90,onemobile,...,0.58520,0.58520,0.585200,0.5852,0.5852,NaN,NaN,NaN,NaN,NaN
1,1,2021-04-11T01:00:00,asc126828,Desktop,America/Chicago,Linux,Chrome-85.04183133,div-gpt-ad-BT-D-Footers,728x90,rhythmone,...,0.33945,0.34875,0.344100,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,2021-04-11T01:00:00,asc126828,Desktop,America/Chicago,Linux,Chrome-85.04183133,div-gpt-ad-BT-D-InLine-1,300x250,undertone,...,0.96000,0.96000,0.960000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,2021-04-11T01:00:00,asc126828,Desktop,America/Chicago,Linux,Chrome-85.04183133,div-gpt-ad-BT-D-O-300x250-1,300x250,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,2021-04-11T01:00:00,asc126828,Desktop,America/Chicago,Linux,Chrome-85.04183133,div-gpt-ad-BT-D-O-300x250-1,300x250,rhythmone,...,0.34410,0.34875,0.346425,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,4995,2021-04-11T01:00:00,asc126828,Desktop,America/New_York,Windows,Chrome-89.04389114,div-gpt-ad-BT-D-InPost-8_1_20,468x60,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4996,4996,2021-04-11T01:00:00,asc126828,Desktop,America/New_York,Windows,Chrome-89.04389114,div-gpt-ad-BT-D-InPost-8_1_20,728x90,medianet,...,0.05828,0.05828,0.058280,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4997,4997,2021-04-11T01:00:00,asc126828,Desktop,America/New_York,Windows,Chrome-89.04389114,div-gpt-ad-BT-D-InPost-8_1_22,468x60,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4998,4998,2021-04-11T01:00:00,asc126828,Desktop,America/New_York,Windows,Chrome-89.04389114,div-gpt-ad-BT-D-InPost-8_1_27,310x260,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4999,4999,2021-04-11T01:00:00,asc126828,Desktop,America/New_York,Windows,Chrome-89.04389114,div-gpt-ad-BT-D-InPost-8_1_33,728x90,,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Describe how you would build a logistic regression model to predict the probability of a bid winning (win) based on the other columns. What features would you select and why?

In [33]:
df.columns

Index(['Unnamed: 0', 'date_hour', 'client', 'device_type', 'time_zone',
       'os_name', 'browser_name', 'ad_unit', 'size', 'bidder', 'bid_range',
       'media_type', 'request_count', 'response_count', 'prebid_win_count',
       'win_count', 'sum_bid', 'sum_time_to_respond', 'median', 'min_bid',
       'max_bid', 'avg_bid', 'sum_2nd_highest_bid', 'sum_prebid_winning_bid',
       'sum_winning_bid', 'sum_nobid', 'sum_timeout', 'win_rate',
       'Count_of_wins'],
      dtype='object')

The logistic regression model can be built for bid winning, having output/target variable as 1 for Yes and 0 for No. The columns that may influence the prediction of target can be, 'request_count','response_count,'sum_bid',sum_time_to_respond-latency affects winning,device_type-dynamics of the devide matter,browser_name, min_bid,max_bid,avg bid,response_time-as latency can affect auction eligibility,date_hour-as time of the day influence bidding.